version: "3.8"

services:
  # goapp:
  #   build: .
  #   container_name: goapp-container
  #   image: goapp-image
  #   ports:
  #     - "5000:5000"
  #   command:
  #     ["./go-docker-app"]
  # PostgreSQL service
  postgres:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    container_name: my-adminer
    ports:
      - "8081:8080"

volumes:
  postgres-data:
